name: CI/CD

on:
  push:
    branches: [main]

jobs:
  setup:
    if: ${{ !contains(github.event.head_commit.message, 'chore:') && !contains(github.event.head_commit.message, 'docs:') }}
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.set-timestamp.outputs.timestamp }}
    steps:
      - name: Set timestamp
        id: set-timestamp
        run: echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT

  backend:
    name: Build & Push Backend
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Build & Push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            shreedhar01/chatapp-backend:latest
            shreedhar01/chatapp-backend:${{ needs.setup.outputs.timestamp }}
          cache-from: type=registry,ref=shreedhar01/chatapp-backend:latest
          cache-to: type=registry,ref=shreedhar01/chatapp-backend:cache,mode=max

  notify-backend:
    name: Notify Discord Backend
    needs: [backend, setup]
    uses: ./.github/workflows/discord.yml
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    with:
      status: ${{ needs.backend.result }}
      job-name: Backend
      commit-message: ${{ github.event.head_commit.message }}
      author: ${{ github.event.head_commit.author.name }}
      timestamp: ${{ needs.setup.outputs.timestamp }}

  frontend:
    name: Build & Push Frontend
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Build & Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          build-args: |
            VITE_API_URL=https://chat.succeedtrading.com/api
          tags: |
            shreedhar01/chatapp-frontend:latest
            shreedhar01/chatapp-frontend:${{ needs.setup.outputs.timestamp }}
          cache-from: type=registry,ref=shreedhar01/chatapp-frontend:latest
          cache-to: type=registry,ref=shreedhar01/chatapp-frontend:cache,mode=max

  notify-frontend:
    name: Notify Discord Frontend
    needs: [frontend, setup]
    uses: ./.github/workflows/discord.yml
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    with:
      status: ${{ needs.frontend.result }}
      job-name: Frontend
      commit-message: ${{ github.event.head_commit.message }}
      author: ${{ github.event.head_commit.author.name }}
      timestamp: ${{ needs.setup.outputs.timestamp }}

  deploy:
    name: Deploy to GCP VM
    needs: [backend, frontend]
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VM_SSH_KEY }}

      - name: Deploy on VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "
            cd ~/chatapp &&
            docker compose pull &&
            docker compose up -d &&
            docker system prune -f
          "

  notify-deploy:
    name: Notify Discord Frontend
    needs: [deploy, setup]
    uses: ./.github/workflows/discord.yml
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    with:
      status: ${{ needs.deploy.result }}
      job-name: Deploy
      commit-message: ${{ github.event.head_commit.message }}
      author: ${{ github.event.head_commit.author.name }}
      timestamp: ${{ needs.setup.outputs.timestamp }}

